### ISSUE TITLE
Read Service Implementation

### ISSUE THREAD

**Issue by kkvarfordt** [cisagov/icsnpp-opcua-binary#26]
## Summary ##

Implement data logging for the OpcUA Read service

## Motivation and context ##

Extend parser functionality to include details related to the Read service

## Tasks: ##
- [x] Implement Binpac parsing logic
- [x] Implement Data Verification (debug) code
- [ ] Implement Analyser code
- [x] Implement Zeek logging

## References: ##

- [Developer Guide](https://github.com/cisagov/icsnpp-opcua-binary/blob/main/developer_guide.md)

**Comment by kkvarfordt** [comment]
This issue is blocked until the Read Service Test Data issue is completed.

**Comment by kkvarfordt** [comment]
Read Service Test Data completed.  Read service implementation moving forward.
