### ISSUE TITLE
ServerFault Service Implementation

### ISSUE THREAD

**Issue by kkvarfordt** [cisagov/icsnpp-opcua-binary#60]
## Summary ##

Implement data logging for the OpcUA ServerFault service

## Motivation and context ##

Extend parser functionality to include details related to the ServerFault service

## Tasks: ##
- [ ] Implement Binpac parsing logic
- [ ] Implement Data Verification (debug) code
- [ ] Implement Analyser code
- [ ] Implement Zeek logging

## References: ##

- [Developer Guide](https://github.com/cisagov/icsnpp-opcua-binary/blob/main/developer_guide.md)

**Comment by kkvarfordt** [comment]
ServerFault Service has been implemented.  See Pull Request #95
